name: christop corley
markdown: redcarpet
highlighter: rouge
timezone: America/Chicago
encoding: UTF-8
permalink: pretty
github_url: "https://github.com/cscorley"
twitter_url: "https://twitter.com/excsc"
email: "mailto:cscorley@crimson.ua.edu"
exclude:
    - Makefile
author_bio: |
    Christopher S. Corley <br />
    PhD student at the
    <a href="http://cscorley.students.cs.ua.edu">University of Alabama</a>.
