title: christop.club
name: Christopher S. Corley
redcarpet:
    extensions:
        - strikethrough
        - tables
        - fenced_code_blocks
        - autolink
        - superscript
        - underline
        - highlighted
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
encoding: UTF-8
permalink: pretty
email: cscorley@crimson.ua.edu
github_username: cscorley
twitter_username: excsc
exclude:
    - Makefile
description: >
    Christopher S. Corley is a PhD candidate at the University of Alabama and
    practicing software engineer.
baseurl: ""
url: "http://christop.club"
