title: christop.club
name: Christopher S. Corley, PhD
redcarpet:
    extensions:
        - strikethrough
        - tables
        - fenced_code_blocks
        - autolink
        - superscript
        - underline
        - highlighted
plugins:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
encoding: UTF-8
permalink: pretty
email: cscorley@crimson.ua.edu
github_username: cscorley
twitter_username: excsc
exclude:
    - Makefile
description: >
    Christopher S. Corley is a software engineer in Chattanooga, TN
baseurl: ""
url: "https://christop.club"
